# Site settings
title: Audiovisual Core
description: Website for the Audiovisual Core standard.
url: "https://tdwg.github.io"
baseurl: "/ac"


js: >-
  

# Build settings
markdown: kramdown
# theme: tdwg-theme-jekyll
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
